### ISSUE TITLE
What's tool chain is required for building Geo-MHYDAS?

### ISSUE THREAD

**Issue by samhjn** [OpenFLUID/openfluid#679] opened 2016-05-25 13:54 UTC
Our team is trying to compile Geo-MHYDAS at OpenFLUID 2.0.2, however we found it cannot be identified by OpenFLUID. We are using Qt 5.5/Boost 1.60/gdal in build-support. Is that tool chain available? And if there is anything else need to be noticed in compiling them? Thank you.

**Comment by fabrejc** [comment] 2016-05-26 06:12
Hello,

Geo-MHYDAS depends on boost, GDAL, GEOS and Qt libraries. The build toolchain is managed by the CMake tool, and mainly relies on the GCC compiler.

Once you have installed the OpenFLUID framework, the dependendency libraries with development support and the toolchain tools, you have to first build and install the libmhydas library, then build and install the Geo-MHYDAS extension for openfluid located in the builderexts directory.

Unless you give me more informations about your operating system and configuration, I cannot give you more instructions.

_Note that Geo-MHYDAS is not currently maintained, the main developer has leaved our team a year ago. These developments will be reactivated in the future._

Sincerly

**Comment by samhjn** [comment] 2016-05-26 16:40
Thank you.
We are working under Windows and  we only tried to build Geo-MHYDAS extension. In order to build faster, We used binary libmhydas published on OpenFLUID website. We can successfully build the extension, but the OpenFLUID builder seems not identify it. And the export table of our build result is less than original DLL file.
Our modification is just for translation. And the modification will be published soon.

**Comment by fabrejc** [comment] 2016-05-27 07:29
OK,
Usually, the problem is coming from dll that cannot be found in the path. Do the depending dll (GEOS, GDAL, Qt, ...) can be accessed using the PATH env var? 
You can track dll that cannot be found using the dependency walker tool (http://www.dependencywalker.com/) and open the geomhydas extension dll in this tool.
In general, it would be more interesting and efficient that you translate the extension using the Qt translation mecanism, as it is implemented in OpenFLUID and its extensions.

Please, could you tell me more about your main objective in using the OpenFLUID simulation platform, and modifying the source code? I looked at your repository  (https://github.com/jylfc0307/OpenFluidPlus) and saw that you have changed the OpenFLUID logo and URL and replaced them by your own. Why?
Maybe it would be more efficient that we collaborate and you provide a real translation in chinese for OpenFLUID using the Qt translation system. Thus, these translations would benefit to others.

Thanks in advance for your answers.
Sincerly

**Comment by samhjn** [comment] 2016-05-27 17:53
Thank you.
Some of problems may not so proper to be discussed in public area... I will send you an e-mail to answer them...
I have found this way to translate. However another team member have translated it in source code. In order to work at what he has done, I translated in the same way...

**Comment by samhjn** [comment] 2016-05-28 05:49
And,,, I have tried the tools... All DLL unavailable it given was system DLLs...

**Comment by fabrejc** [comment] 2016-06-15 14:58
Is the problem solved?

**Comment by fabrejc** [comment] 2016-08-29 06:52
No comment followed in the last 2 months, so closing the ticket

**Closed by fabrejc** 2016-08-29 06:52 UTC
Labels: support
