### ISSUE TITLE
QDir::mkpath can produce exception when saving project

### ISSUE THREAD

**Issue by chataignerm** [OpenFLUID/openfluid#734] opened 2017-07-24 09:35 UTC
Exception produced in builder at project saving, after creating it and adding simulator, generators and observer.
Path passed to QDir::mkpath seems to be empty.

Qt message :
QDir::mkpath: Empty or null file name

**Comment by fabrejc** [comment] 2017-11-06 14:07
Cannot reproduce the problem. Closing it.

**Closed by fabrejc** 2017-11-06 14:07 UTC
Labels: builder, duplicate-invalid-not reproduced, unconfirmed bug
